config/routes.rb
Rails.application.routes.draw do
  resources :markers
  resources :categories
  resources :types

  get 'api/categories', to: 'categories#news'
  get 'update/:id', to: 'categories#public_active', as: 'public_active'

  root 'markers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, optional: true
  has_many   :categories
  has_many   :markers, dependent: :destroy
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :type
  belongs_to :category
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :markers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :public_active]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def news
    categories = Category.where('category_id is null')
    hash = categories.map{|category| { "Categoria" => category.name, "Subcategoria" => category.categories.map { |subc| subc.name } }}
    # hash = categories.map{|category| { "Categoria" => category.name, "Subcategoria" => category.categories.map { |subc| subc.markers.map { |marker| marker.url_address } } }}
    pretty_hash = JSON.pretty_generate(hash)
    
    render json: pretty_hash
  end

  # GET /categories/new
  def new
    @category = Category.new
    @categories = Category.all
  end

  def public_active
    @category.toggle!(:public)
    redirect_to categories_path
  end

  # GET /categories/1/edit
  def edit
    @categories = Category.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :public, :category_id)
    end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all
    @marker = Marker.new

    @types = Type.all

    @categories = Category.all
    @general_categories = Category.where('category_id is null')

    respond_to do |format|
      format.html {}
      format.js { @marker }
    end
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
    @types = Type.all
    @categories = Category.all

  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render :show, status: :created, location: @marker }
        format.js { @marker }
      else
        format.html { render :new }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
        format.js { render :index }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
        format.js { @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
        format.js { render :index }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:url_address, :type_id, :category_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    @query = Type.joins(:markers).group(:name).count

  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nombre de la Categoría" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mt-2">
    <%= form.label "Pública" %>
    <%= form.check_box :public %>
  </div>

  
  <div class="field my-3"> 
    <%= form.label 'Subcategoría de:' %>
    <%= form.collection_select :category_id, @categories, :id, :name, {prompt: 'Selecciona una categoria'}, {class: 'custom-select'} %><span class="font-weight-bold">Omitir si es Categoria general</span>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-success my-2' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="my-3 text-center">Edición de Categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Mostrar', @category, class: 'btn btn-primary mt-2' %>
<%= link_to 'Volver', categories_path, class: 'btn btn-primary mt-2' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Categorias</h1>

<table class="table table-striped my-3">
  <thead class="thead-dark">
    <tr>
      <th>Categoria</th>
      <th>Privacidad</th>
      <th style="text-align: center">Cambiar Privacidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.public ? "Publica" : "Privada" %></td>
        <td style="text-align: center"><%= link_to 'X', public_active_path(category.id) %></td>
        <td><%= link_to 'Mostrar', category %></td>
        <td><%= link_to 'Editar', edit_category_path(category) %></td>
        <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Volver', root_path, class: 'btn btn-primary mt-2' %>
<%= link_to 'Nueva Categoria', new_category_path, class: 'btn btn-primary mt-2' %>

app/views/categories/new.html.erb
<h1 class="text-center my-2 font-weight-bold">Nueva Categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Volver', categories_path, class: 'btn btn-primary' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Privacidad:</strong>
  <%= @category.public ? "Público" : "Privado" %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @category.category.nil? ? "General" : @category.category.name.capitalize %>
</p>

<%= link_to 'Editar', edit_category_path(@category), class: 'btn btn-primary mt-2' %>
<%= link_to 'Volver', categories_path, class: 'btn btn-primary mt-2' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaMarcadores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_with(model: @marker, remote: true, data: {confirm: 'Are you sure?'}) do |form| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-row mt-2">
      <div class="col">
        <%= form.text_field :url_address, placeholder: 'URL...', class: 'form-control' %>
      </div>
      <div class="col">
        <%= form.collection_select :type_id, @types, :id, :name, {prompt: 'Selecciona un tipo...'}, {class: 'custom-select'} %>
      </div>
      <div class="col">
        <%= form.collection_select :category_id, @categories, :id, :name, {prompt: 'Selecciona una categoría...'}, {class: 'custom-select'} %>
      </div>
      <div class="col">
        <%= form.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>

<% end %>

app/views/markers/_marker.html.erb
<% if marker.category.public %>
<tr id="marker_<%= marker.id %>">
    <td><%= marker.url_address %></td>
    <td><%= marker.type.name %></td>
    <td><%= marker.category.name %></td>
    <td><%= link_to 'Ver', marker %></td>
    <td><%= link_to 'Editar', edit_marker_path(marker), remote: true %></td>
    <td><%= link_to 'Eliminar', marker, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>

app/views/markers/create.js.erb
document.getElementById('tbody').innerHTML += '<%= j render @marker %>'

app/views/markers/edit.html.erb
<h1 class='text-center my-3'>Edición</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Mostrar', @marker, class: 'btn btn-primary mt-3' %>
<%= link_to 'Volver', markers_path, class: 'btn btn-primary mt-3' %>

app/views/markers/edit.js.erb
document.getElementById('marker_<%= @marker.id %>').innerHTML = '<td colspan="2"><%= j render 'form', marker: @marker %></td>'

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Marcadores</h1>

<%= link_to 'Administrar Categorías', categories_path, class: 'btn btn-primary' %>
<%= link_to 'Administrar Tipos', types_path, class: 'btn btn-primary' %>

<%= render 'form' %>

<table class="table table-striped mt-3">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Direccion URL</th>
      <th scope="col">Tipo</th>
      <th scope="col">Categoria</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody id="tbody">
      <%= render @markers %>
  </tbody>
</table>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dirección URL:</strong>
  <%= @marker.url_address %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @marker.type.name %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @marker.category.name %>
</p>

<%= link_to 'Editar', edit_marker_path(@marker), class: 'btn btn-primary' %>
<%= link_to 'Volver', markers_path, class: 'btn btn-primary' %>

app/views/markers/update.js.erb
document.getElementById('marker_<%= @marker.id %>').innerHTML = '<%= j render @marker %>'

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Crear', class: 'btn btn-success my-3' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-3">Tipos</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name.capitalize %></td>
        <td><%= link_to 'Mostrar', type %></td>
        <td><%= link_to 'Editar', edit_type_path(type) %></td>
        <td><%= link_to 'Eliminar', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Volver', root_path, class: 'btn btn-primary' %>
<%= link_to 'Crear nuevo tipo', new_type_path, class: 'btn btn-primary' %>

<br>

<h2 class="text-center my-3 font-weight-bold">Cantidad de Marcadores por Tipo</h2>

<%= pie_chart @query %>

<br>

app/views/types/new.html.erb
<h1>Nuevo Tipo</h1>

<%= render 'form', type: @type %>

<%= link_to 'Volver', types_path, class: 'btn btn-primary' %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @type.name.capitalize %>
</p>

<%= link_to 'Editar', edit_type_path(@type), class: 'btn btn-primary' %>
<%= link_to 'Volver', types_path, class: 'btn btn-primary' %>